spring: 
  application: 
    name: TierService
  kafka: 
    bootstrap-servers: localhost:9092
    consumer: 
      group-id: orderInfoGroup
    listener: 
      concurrency: 3
    topic: orderInfo
  data: 
    mongodb:
      uri: mongodb://127.0.0.1:27017/TierTest
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    lock: 
      pattern: tierService.evaluation.lock
      timeout: 20
server: 
  port: 8082
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8080/eureka/
